// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ServerDiscoveryInfo {
    /**
     * Creates a new ServerDiscoveryInfo instance.
     * @param {Partial<ServerDiscoveryInfo>} [$$source = {}] - The source object to create the ServerDiscoveryInfo.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("IP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IP"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Port"] = "";
        }
        if (!("AnonymousAllowed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["AnonymousAllowed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerDiscoveryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerDiscoveryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerDiscoveryInfo(/** @type {Partial<ServerDiscoveryInfo>} */($$parsedSource));
    }
}
