//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../../../changeme/internal/config/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "client:discover-servers": $$createType0,
        "transfers": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = config$0.ServerDiscoveryInfo.createFrom;
const $$createType1 = config$0.TransferInfo.createFrom;

configure();
